server:
  port: 9091

spring:
  application:
    name: facebook-oauth

security:
  oauth2:
    client:
      clientId: <app-id>
      clientSecret: <secret-key>
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
